import '@stream-io/video-react-sdk/dist/css/styles.css';
import './globals.css';

import { RedirectToSignIn, SignedOut } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

import ConvexClerkProvider from '@/components/providers/ConvexClerkProvider';
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import { NavbarWrapper } from '@/components/shared';

const nunito = Nunito({
	subsets: ['cyrillic', 'latin'],
	variable: '--font-nunito',
	weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ConvexClerkProvider>
			<html lang="en" suppressHydrationWarning>
				<body className={`${nunito.className} antialiased`}>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange>
						<div className="min-h-screen">
							<NavbarWrapper />
							<main className="px-4 sm:px-6 lg:px-8">{children}</main>
						</div>

						<SignedOut>
							<RedirectToSignIn />
						</SignedOut>
					</ThemeProvider>
					<Toaster />
				</body>
			</html>
		</ConvexClerkProvider>
	);
}
